# numpy

In [1]:
import numpy as np

# one dimensional array

In [11]:
#creating an array using a python list
x=np.array([22,33,44,55])
x

array([22, 33, 44, 55])

In [3]:
x.size

4

In [4]:
#1d=vector
#2d=matrics
#3d=cube
#nd=.....
x.shape

(4,)

In [5]:
 # For checking the dimension of an array we can use the x.ndim property
x.ndim

1

In [6]:
arr1d=np.arange(10)
arr1d
#it will create an array with 10 numbers it is same as range function python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Now we will create 2-dimensional array

In [7]:
arr2d=np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])

In [8]:
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [10]:
arr2d.shape
#in the below out put(4,3) it shows the above array has 4 rows and 3 columns

(4, 3)

In [11]:
#now we have an other way of creating an array by using numpay functions like arange function

arr2d=np.arange(20).reshape(1,20)
# arr2d=np.arange(20).reshape(20,1)
# arr2d=np.arange(20).reshape(10,2)
# arr2d=np.arange(20).reshape(4,5)
# arr2d=np.arange(20).reshape(5,4)
# arr2d=np.arange(20).reshape(2,10)
#it shows that arange(20) create an array with 20 elements and rehsape contain 2 digit like (1,20) it means 1 row and 20 coloums same as others 

In [12]:
arr2d
#the below output shows that its looks like 1d array but [[ brackets shows it is 2d array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [13]:
arr2d.shape
#The below output(1,20) shows the, above output contain 1 row and 20 colums

(1, 20)

In [14]:
arr2d.ndim

2

In [16]:
#we can also reshape this 2d array into 1d array by using the following code
arr2d.reshape(20)
#single bracket [ shows it has 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# we can also reshape array from 2d to 1d by using the following functions

In [18]:
#arr2d.reshape(20)
#arr2d.flatten()
#arr2d.ravel()

In [19]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
#scaler and scaler has no direction
arr=np.array(10)
arr

array(10)

In [13]:
arr.ndim

0

In [25]:
# 1d vector
arr=np.array([10])
arr

array([10])

In [26]:
# 2d matrix
arr=np.array([[10]])
arr

array([[10]])

In [15]:
arr3d=np.arange(64).reshape(4,4,4)#(depth,row,colums)it means make 4 matrics with 4 columns and 4 rowsarr2d
                                  #(matricsNum,row,colums)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [22]:
arr2d=np.arange(20).reshape(2,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [23]:
#for slicing of 2d array we will write the first, row number and then the column, as example below 1 row and 8th colummn
arr2d[1,8]

18

In [24]:
#another way we will write it separate like this
arr2d[1][8]

18

In [28]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [29]:
#for slicing of 3d array select metrix num then the row num and then the colum number
arr3d[2,1,2]

38

In [30]:
#we have an 1d array like below and we want to multipy it with 2, all elements of 1d array * by 2
x

array([22, 33, 44, 55])

In [31]:
x*2

array([ 44,  66,  88, 110])

In [32]:
x/10

array([2.2, 3.3, 4.4, 5.5])

In [33]:
arr3d*10

array([[[  0,  10,  20,  30],
        [ 40,  50,  60,  70],
        [ 80,  90, 100, 110],
        [120, 130, 140, 150]],

       [[160, 170, 180, 190],
        [200, 210, 220, 230],
        [240, 250, 260, 270],
        [280, 290, 300, 310]],

       [[320, 330, 340, 350],
        [360, 370, 380, 390],
        [400, 410, 420, 430],
        [440, 450, 460, 470]],

       [[480, 490, 500, 510],
        [520, 530, 540, 550],
        [560, 570, 580, 590],
        [600, 610, 620, 630]]])

In [34]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [35]:
arr2d*5

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [36]:
arr2d*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])