In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
np. __version__

'1.20.3'

In [5]:
x=np.zeros(5, dtype="int")

In [6]:
x

array([0, 0, 0, 0, 0])

In [7]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.empty((6,6))

array([[5.62949964e+014, 4.76371477e-313, 2.49292202e-306,
        3.82368606e-297, 1.95729482e-293, 1.12865568e+102],
       [1.33856861e-152, 2.59345433e+161, 6.01334434e-154,
        9.82158062e+252, 7.22762050e+159, 1.02189781e-152],
       [7.20185265e+159, 1.24003793e+180, 9.10016856e+276,
        4.31131207e+174, 5.51999516e+228, 4.17521494e+199],
       [6.01334434e-154, 9.92132478e+247, 4.46811730e-091,
        2.44041296e-154, 9.10016855e+276, 4.31131207e+174],
       [2.50520622e+262, 3.32234295e+257, 8.72733418e+183,
        1.96097649e+243, 5.98129759e-154, 3.70174749e-312],
       [1.33360310e+241, 2.95763773e-310, 4.44442142e-312,
        3.38715345e-307, 1.33360328e+241, 2.36008372e-310]])

In [11]:
list=[12,22,33,44,55]

In [12]:
list1=np.array(list)

In [13]:
list1

array([12, 22, 33, 44, 55])

In [14]:
np.arange(10,100,5) #start, stop, step

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [15]:
list1.shape

(5,)

In [16]:
list1.size

5

In [17]:
#0D Array
array0=np.array(5)

In [18]:
array0

array(5)

In [19]:
arr1=np.array([1,2,3,4,5]) #1D array

In [20]:
arr1

array([1, 2, 3, 4, 5])

In [21]:
arr2=np.array([[22,33,44,55,66,77]])

In [22]:
arr2

array([[22, 33, 44, 55, 66, 77]])

In [23]:
arr3=np.array([[[11,22,33,44,55,66,77,88,99]]])

In [24]:
arr3

array([[[11, 22, 33, 44, 55, 66, 77, 88, 99]]])

# Another Method to create arrays

In [25]:
arr2d=np.arange(20).reshape(5,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
arr3d=np.arange(30).reshape(10,3)
arr3d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [27]:
arr3d.dtype

dtype('int32')

In [28]:
arr3d.ndim

2

# Random Number numpy

In [29]:
from  numpy import random
x=random.randint(10)  #it will generate integer random number within the value of 10

In [30]:
x

4

In [31]:
y=random.randint(100)
y

52

In [32]:
z=random.rand()
z             #it will geberate float random numbers

0.2041257401986467

# creating array from Random  numbers

In [67]:
r=random.randint(5, size=([1,2,3]))

In [68]:
r

array([[[4, 3, 0],
        [0, 3, 2]]])

In [35]:
rr=random.rand(20)

In [36]:
rr

array([0.49331576, 0.18045718, 0.23748661, 0.427437  , 0.28825596,
       0.6960916 , 0.63999267, 0.60079707, 0.92076906, 0.83144182,
       0.35922468, 0.96410206, 0.90058983, 0.07223654, 0.74635404,
       0.23661817, 0.38978152, 0.93836132, 0.73070933, 0.58532915])

In [73]:
x=random.choice([1,2,3,4])  #it will extract randomly any number from the given array

In [74]:
x

3

In [39]:
mylist=(["Farhan","daud","minhal"])
shuffle=random.shuffle(mylist)               #it will shuffle the elemnt from my given array


In [40]:
shuffle

In [41]:
mylist

['Farhan', 'daud', 'minhal']

In [42]:
per=random.permutation(mylist)   #permutation are same as shuffle

In [43]:
mylist

['Farhan', 'daud', 'minhal']

# Indexing 

In [44]:
ind=np.array([1,2,3,4,5,6])

In [45]:
ind

array([1, 2, 3, 4, 5, 6])

In [46]:
ind[1]

2

In [47]:
ind[2]

3

In [48]:
ind[3]

4

In [49]:
ind[0]

1

# Boolean indexing

In [50]:
ind[x>4]

array([], shape=(0, 6), dtype=int32)

# fancy indexing

In [51]:
ind[[2,3]]  #it will return multiple values by indexing number that is we give 

array([3, 4])

In [52]:
x=random.randint(10)

In [53]:
x

6

# Slicing

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [55]:
arr[1:3]

array([2, 3])

In [56]:
arr[0:3]

array([1, 2, 3])

In [57]:
arr[4:]

array([5, 6, 7])

In [58]:
arr[ : 3]

array([1, 2, 3])

# Negative Slicing

In [59]:
arr=np.array([1,2,3,4,5,6])

In [60]:
array[-1:-4:-1]

NameError: name 'array' is not defined

In [ ]:
arr2d=np.arange(20).reshape(5,4)

In [ ]:
arr2d


In [ ]:
arr2d[0][3]

In [ ]:
arr2d[0]

In [ ]:
arr1d=np.array([1,2,3,4,5,6])

In [ ]:
arr1d

In [ ]:
arr1d[1:3]

In [ ]:
arr1d[-1:-3:-1]

In [ ]:
arr2d

In [ ]:
arr2d[3:5,0:2]

In [ ]:
arr1=([1,2,3,4])
x=arr1.copy()
arr1[0]=42

print(arr1)
print(x)

In [ ]:
array=([1,2,3,3,4,5,66,66])

In [ ]:
array

In [ ]:
x=array.copy()
array[3]=4

In [ ]:
print(array)
print(x)

# view

In [ ]:
array=np.array([1,2,3,4])

In [ ]:
array

In [ ]:
y=array.view()
array[1]=1
print(array)
print(y)

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

# Concatenation


In [75]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [76]:
arr2=np.array([[9,10,11,12],[13,14,15,16]])

In [79]:
con=np.concatenate((arr1,arr2),axis=0)

In [80]:
con

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
con=np.dstack((arr1,arr2))

In [ ]:
con

In [81]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
split=np.split(a,[2,5])

In [84]:
split

[array([1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [ ]:
a.ndim

In [ ]:
a.shape